name: amath
channels:
  - conda-forge
dependencies:
  - mnist
  - matplotlib
  - numpy
  - pandas
  - sparse
  - scikit-learn
  - opencv
  - nbgitpuller
  - jupyterlab
  - nodejs
  - pip
  - pip:
    - python-mnist
